// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Buttons nav field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Buttons nav
   * - **API ID Path**: header.buttons_nav
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttons_nav: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * logo field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | PortfolioSlice
  | AboutSlice
  | SkillsSlice
  | HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = HeaderDocument | PageDocument;

/**
 * Primary content in *About → Default → Primary*
 */
export interface AboutSliceDefaultPrimary {
  /**
   * image about field in *About → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.image_about
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image_about: prismic.ImageField<never>;

  /**
   * description field in *About → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * title field in *About → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * image bg field in *About → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.image_bg
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image_bg: prismic.ImageField<never>;

  /**
   * section id field in *About → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.section_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_id: prismic.KeyTextField;
}

/**
 * Default variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *About*
 */
type AboutSliceVariation = AboutSliceDefault;

/**
 * About Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: About
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSlice = prismic.SharedSlice<"about", AboutSliceVariation>;

/**
 * Item in *Hero → Default → Primary → social links*
 */
export interface HeroSliceDefaultPrimarySocialLinksItem {
  /**
   * link social field in *Hero → Default → Primary → social links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: link social
   * - **API ID Path**: hero.default.primary.social_links[].link_social
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link_social: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * icon social field in *Hero → Default → Primary → social links*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.social_links[].icon_social
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon_social: prismic.ImageField<never>;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * image hero field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.image_hero
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image_hero: prismic.ImageField<never>;

  /**
   * intro text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: intro text
   * - **API ID Path**: hero.default.primary.intro_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  intro_text: prismic.KeyTextField;

  /**
   * name field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: name
   * - **API ID Path**: hero.default.primary.name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * role field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: role
   * - **API ID Path**: hero.default.primary.role
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  role: prismic.KeyTextField;

  /**
   * cv file field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: cv file
   * - **API ID Path**: hero.default.primary.cv_file
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  cv_file: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * social links field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.social_links[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  social_links: prismic.GroupField<
    Simplify<HeroSliceDefaultPrimarySocialLinksItem>
  >;

  /**
   * section id field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.section_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_id: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *Portfolio → Default → Primary → projects cards*
 */
export interface PortfolioSliceDefaultPrimaryProjectsCardsItem {
  /**
   * project image field in *Portfolio → Default → Primary → projects cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.default.primary.projects_cards[].project_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  project_image: prismic.ImageField<never>;

  /**
   * description field in *Portfolio → Default → Primary → projects cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.default.primary.projects_cards[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * tools field in *Portfolio → Default → Primary → projects cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.default.primary.projects_cards[].tools
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  tools: prismic.RichTextField;
}

/**
 * Primary content in *Portfolio → Default → Primary*
 */
export interface PortfolioSliceDefaultPrimary {
  /**
   * title field in *Portfolio → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * projects cards field in *Portfolio → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.default.primary.projects_cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  projects_cards: prismic.GroupField<
    Simplify<PortfolioSliceDefaultPrimaryProjectsCardsItem>
  >;

  /**
   * section id field in *Portfolio → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.default.primary.section_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_id: prismic.KeyTextField;
}

/**
 * Default variation for Portfolio Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PortfolioSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PortfolioSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Portfolio*
 */
type PortfolioSliceVariation = PortfolioSliceDefault;

/**
 * Portfolio Shared Slice
 *
 * - **API ID**: `portfolio`
 * - **Description**: Portfolio
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PortfolioSlice = prismic.SharedSlice<
  "portfolio",
  PortfolioSliceVariation
>;

/**
 * Primary content in *Sayed → Default → Primary*
 */
export interface SayedSliceDefaultPrimary {
  /**
   * dfds field in *Sayed → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: sdfsdfds
   * - **API ID Path**: sayed.default.primary.dfds
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  dfds: prismic.KeyTextField;
}

/**
 * Default variation for Sayed Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SayedSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SayedSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Sayed*
 */
type SayedSliceVariation = SayedSliceDefault;

/**
 * Sayed Shared Slice
 *
 * - **API ID**: `sayed`
 * - **Description**: Sayed
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SayedSlice = prismic.SharedSlice<"sayed", SayedSliceVariation>;

/**
 * Item in *Skills → Default → Primary → frontend skills *
 */
export interface SkillsSliceDefaultPrimaryFrontendSkillsItem {
  /**
   * title field in *Skills → Default → Primary → frontend skills *
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.frontend_skills[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * image Skill field in *Skills → Default → Primary → frontend skills *
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.frontend_skills[].image_skill
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image_skill: prismic.ImageField<never>;
}

/**
 * Item in *Skills → Default → Primary → Styling UI*
 */
export interface SkillsSliceDefaultPrimaryStylingUiItem {
  /**
   * title field in *Skills → Default → Primary → Styling UI*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.styling_ui[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * image Skill field in *Skills → Default → Primary → Styling UI*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.styling_ui[].image_skill
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image_skill: prismic.ImageField<never>;
}

/**
 * Item in *Skills → Default → Primary → Tools Workflow*
 */
export interface SkillsSliceDefaultPrimaryToolsWorkflowItem {
  /**
   * title field in *Skills → Default → Primary → Tools Workflow*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.tools_workflow[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * image Skill field in *Skills → Default → Primary → Tools Workflow*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.tools_workflow[].image_skill
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image_skill: prismic.ImageField<never>;
}

/**
 * Primary content in *Skills → Default → Primary*
 */
export interface SkillsSliceDefaultPrimary {
  /**
   * frontend skills  field in *Skills → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.frontend_skills[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  frontend_skills: prismic.GroupField<
    Simplify<SkillsSliceDefaultPrimaryFrontendSkillsItem>
  >;

  /**
   * Styling UI field in *Skills → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.styling_ui[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  styling_ui: prismic.GroupField<
    Simplify<SkillsSliceDefaultPrimaryStylingUiItem>
  >;

  /**
   * Tools Workflow field in *Skills → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.tools_workflow[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  tools_workflow: prismic.GroupField<
    Simplify<SkillsSliceDefaultPrimaryToolsWorkflowItem>
  >;

  /**
   * section id field in *Skills → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.section_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_id: prismic.KeyTextField;
}

/**
 * Default variation for Skills Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SkillsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SkillsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Skills*
 */
type SkillsSliceVariation = SkillsSliceDefault;

/**
 * Skills Shared Slice
 *
 * - **API ID**: `skills`
 * - **Description**: Skills
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SkillsSlice = prismic.SharedSlice<"skills", SkillsSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HeaderDocument,
      HeaderDocumentData,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutSlice,
      AboutSliceDefaultPrimary,
      AboutSliceVariation,
      AboutSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimarySocialLinksItem,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      PortfolioSlice,
      PortfolioSliceDefaultPrimaryProjectsCardsItem,
      PortfolioSliceDefaultPrimary,
      PortfolioSliceVariation,
      PortfolioSliceDefault,
      SayedSlice,
      SayedSliceDefaultPrimary,
      SayedSliceVariation,
      SayedSliceDefault,
      SkillsSlice,
      SkillsSliceDefaultPrimaryFrontendSkillsItem,
      SkillsSliceDefaultPrimaryStylingUiItem,
      SkillsSliceDefaultPrimaryToolsWorkflowItem,
      SkillsSliceDefaultPrimary,
      SkillsSliceVariation,
      SkillsSliceDefault,
    };
  }
}
