import type { Metadata } from "next";
import {Lato } from "next/font/google";
import "./globals.css";
import { PrismicNextImage, PrismicNextLink } from "@prismicio/next";
import Link from "next/link";
import Header from "@/components/Header";
const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"], // Add desired weights here
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 

  return (
    <html lang="en">
      <body className={`${lato.variable} antialiased`}>
       <Header />
       <main>
         {children}
       </main>

      </body>
    </html>
  );
}
