import type { Metadata } from "next";
import { Lato, Orbitron, Saira_Semi_Condensed } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";
import ThemeToggle from "@/components/BtnDarkMode";
import Footer from "@/components/Footer";

const orbitrin = Orbitron({
  variable: "--font-orbitron",

  weight: ["400", "700", "900"], 

  
  // Add desired weights here
});
const sairaSemi = Saira_Semi_Condensed({
  variable: "--font-sairaSemi",

  weight: ["400", "700", "900"], 
  subsets:['latin'],

  // Add desired weights here
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const revalidate = 300;

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-scroll-behavior="smooth" data-theme='dark' >
      <body className={` ${orbitrin.variable} ${sairaSemi.variable} antialiased`}>
        <Header />
        <main>{children}</main>
        <Footer/>

    <ThemeToggle/>
      </body>
    </html>
  );
}
